(define (swapper s1 s2 slist)
  (if (null? slist)
      '()
      (cond ((eq? s1 (car slist))
	     (cons s2 (swapper s1 s2 (cdr slist))))
	    ((eq? s2 (car slist))
	     (cons s1 (swapper s1 s2 (cdr slist))))
	    (else (cons (car slist) (swapper s1 s2 (cdr slist)))))))

(define i (swapper 1 4 (list 1 3 5 4 'wse 6)))
